name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkoutz

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/minha-api:latest .

      - name: Publicar imagem
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/minha-api:latest